{
 "title": "Lambda",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gesamt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(heatpump_electricenergy) * 0.27 as \"Kosten (Gesamt)\"\r\nFROM heatpump "
    },
    {
     "rawSql": "SELECT MAX(heatpump_heatenergy) AS \"Wärme\"\r\nFROM heatpump "
    },
    {
     "rawSql": "SELECT MAX(heatpump_electricenergy) AS \"Energie\"\r\nFROM heatpump "
    },
    {
     "rawSql": "SELECT MAX(heatpump_heatenergy) / MAX(heatpump_electricenergy)  AS \"CoP\"\r\nFROM heatpump "
    }
   ]
  },
  {
   "title": "Aktuelle Jahr",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (difference * 0.27) as \"Kosten\" from heatpump_current_electric "
    },
    {
     "rawSql": "SELECT heatpump_difference AS \"Wärme\"\r\nFROM heatpump_current_heat "
    },
    {
     "rawSql": "SELECT difference AS \"Energie\"\r\nFROM heatpump_current_electric"
    },
    {
     "rawSql": "select cop_ratio as \"CoP\" from heatpump_cop_current"
    }
   ]
  },
  {
   "title": "Kompressor Leistung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heatpump_compressorrating as \"Leistung\" FROM heatpump ORDER BY event_timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT boiler_hightemp FROM heatpump ORDER BY event_timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ambient_temperaturecalculated FROM heatpump ORDER BY event_timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Akt Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heatpump_operatingstate as value FROM heatpump ORDER BY event_timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Heatpump Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp, (heatpump_inverteractualpower / 1000) as \"Actual\" FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    },
    {
     "rawSql": "SELECT event_timestamp, Heatpump_ActualHeatingCapacity as \"Capacity\" FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  },
  {
   "title": "WP Vorlauf/Rücklauf",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp,heatpump_flowlinetemp as \"Vorlauf\", heatpump_returnlinetemp as \"Rücklauf\" FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp, boiler_hightemp  FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  },
  {
   "title": "Vorlauf OG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp,  heatingcircuit_2_flowtemp  FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  },
  {
   "title": "Vorlauf EG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp, heatingcircuit_1_flowtemp  FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  },
  {
   "title": "Temperatur außen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT event_timestamp, ambient_temperaturecalculated as \"Temperatur\" FROM heatpump  WHERE event_timestamp BETWEEN $__timeFrom() AND $__timeTo() GROUP BY event_timestamp"
    }
   ]
  }
 ]
}